// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Todo struct {
	ID          int64
	Name        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ValidTill   time.Time
	Completed   bool
	CompletedAt sql.NullTime
}
