// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Todo struct {
	ID          int64
	Name        sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ValidTill   sql.NullTime
	Completed   sql.NullBool
	CompletedAt sql.NullTime
}
